keyboards = [
  "keychron-keychron-q10-keyboard",
  "keychron-keychron-q10",
  "keychron-keychron-q10-system-control",
  "keychron-keychron-q10-consumer-control",
]

[[default_layouts]]
0 = [
  "kitty",
]
1 = [
  "discord",
  "firefox",
]
