{
  config,
  lib,
  pkgs,
  ...
}:

with lib;
with lib.plusultra;
let
  cfg = config.plusultra.system.nix;
in
{
  options.plusultra.system.nix = with types; {
    enable = mkBoolOpt true "Whether or not to manage nix configuration.";
  };

  config = mkIf cfg.enable {
    environment.systemPackages = with pkgs; [
      git
      deploy-rs
      nixfmt-tree
      nix-index
      nix-prefetch-git
    ];

    system.primaryUser = config.plusultra.user.name;
    nix =
      let
        users = [
          "root"
          config.plusultra.user.name
        ];
      in
      {
        settings = {
          experimental-features = "nix-command flakes";
          http-connections = 50;
          warn-dirty = false;
          log-lines = 50;
          sandbox = false;
          trusted-users = users;
          allowed-users = users;

          # @NOTE(jakehamilton): This configuration is generated by nix-installer so I'm adding it here in
          # case it becomes important.
          extra-nix-path = "nixpkgs=flake:nixpkgs";
          build-users-group = "nixbld";
        };

        # flake-utils-plus
        generateRegistryFromInputs = true;
        generateNixPathFromInputs = true;
        linkInputs = true;

        package = pkgs.nixVersions.latest;
      };
  };
}
