{ self, ... }:
{
  flake.nixosConfigurations.noel = self.lib.mkNixos {
    system = "x86_64-linux";
    hostName = "noel";
    modules = with self.nixosModules; [
      nix-settings
      users-juggeli
      home-manager
      networking
      boot
      zfs
      impermanence
      tmpfs
      openssh
      tailscale
      agenix
      agenix-shared
      doas
      podman
      tools-misc
      hardware-audio
      hardware-storage
      hardware-logitech
      system-fonts
      system-locale
      system-time
      services-printing
      theming
      hyprland
      hyprlock
      hypridle
      wlsunset
      logitech-mouse-resume
      desktop-gtk
      desktop-qt
      desktop-mako
      desktop-rofi
      desktop-electron
      onepassword
      avahi
      flatpak
      syncthing
      earlyoom
      gaming
      kdeconnect
      dev-rust

      home-impermanence
      home-process-anime
      home-ghostty
      home-wezterm
      home-fish
      home-tmux
      home-bat
      home-btop
      home-jq
      home-yazi
      home-lazygit
      home-gh
      home-nh
      home-ai-agents
      home-pi
      home-opencode
      home-claude-code
      home-cw
      home-ffmpeg
      home-imv
      home-sshfs
      home-ab-av1
      home-nushell
      home-neovim
      home-git
      home-direnv
      home-devtools
      home-hdd-scraper
      home-sorter
      home-kitty
      home-mpv
      home-discord
      home-firefox
      home-chrome
      home-via
      home-pdf
      home-crypto
      home-hydrus
      home-obsidian
      home-anytype
      home-vscode
      home-comfyui
      home-lmstudio
      home-waybar

      ../../hosts/noel
    ];
  };
}
